melee_weapon_stats = {
    'club': {'weapon type': 'simple', 
             'damage die': (4,), 
             'damage type': 'bludgeoning', 
             'bonus attribute': 'strength', 
             'weapon properties': ['light']}, 
    'greatclub': {'weapon type': 'simple', 
                  'damage die': (8,), 
                  'damage type': 'bludgeoning', 
                  'bonus attribute': 'strength', 
                  'weapon properties': ['two handed']}, 
    'mace': {'weapon type': 'simple', 
             'damage die': (6,), 
             'damage type': 'bludgeoning', 
             'bonus attribute': 'strength', 
             'weapon properties': []}, 
    'sickle': {'weapon type': 'simple', 
               'damage die': (4,), 
               'damage type': 'slashing', 
               'bonus attribute': 'strength', 
               'weapon properties': ['light']}, 
    'flail': {'weapon type': 'martial', 
              'damage die': (8,), 
              'damage type': 'bludgeoning', 
              'bonus attribute': 'strength', 
              'weapon properties': []}, 
    'glaive': {'weapon type': 'martial', 
               'damage die': (10,), 
               'damage type': 'slashing', 
               'bonus attribute': 'strength', 
               'weapon properties': ['heavy', 'reach', 'two handed']}, 
    'great axe': {'weapon type': 'martial', 
                  'damage die': (12,), 
                  'damage type': 'slashing', 
                  'bonus attribute': 'strength', 
                  'weapon properties': ['heavy', 'two handed']}, 
    'great sword': {'weapon type': 'martial', 
                    'damage die': (6, 6), 
                    'damage type': 'slashing', 
                    'bonus attribute': 'strength', 
                    'weapon properties': ['heavy', 'two handed']}, 
    'halberd': {'weapon type': 'martial', 
                'damage die': (10,), 
                'damage type': 'slashing', 
                'bonus attribute': 'strength', 
                'weapon properties': ['heavy', 'reach', 'two handed']}, 
    'lance': {'weapon type': 'martial', 
              'damage die': (12,), 
              'damage type': 'piercing', 
              'bonus attribute': 'strength', 
              'weapon properties': ['reach', 'special:']}, 
    'maul': {'weapon type': 'martial', 
             'damage die': (6, 6), 
             'damage type': 'bludgeoning', 
             'bonus attribute': 'strength', 
             'weapon properties': ['heavy', 'two handed']}, 
    'morning star': {'weapon type': 'martial', 
                     'damage die': (8,), 'damage type': 
                     'piercing', 'bonus attribute': 'strength', 
                     'weapon properties': []}, 
    'pike': {'weapon type': 'martial', 
             'damage die': (10,), 
             'damage type': 'piercing', 
             'bonus attribute': 'strength', 
             'weapon properties': ['heavy', 'reach', 'two handed']}, 
    'rapier': {'weapon type': 'martial', 
               'damage die': (8,), 
               'damage type': 'piercing', 
               'bonus attribute': ('strength', 'dexterity'), 
               'weapon properties': ['finesse']}, 
    'scimitar': {'weapon type': 'martial', 
                 'damage die': (6,), 
                 'damage type': 'slashing', 
                 'bonus attribute': ('strength', 'dexterity'), 
                 'weapon properties': ['finesse', 'light']}, 
    'short sword': {'weapon type': 'martial', 
                    'damage die': (6,), 
                    'damage type': 'piercing', 
                    'bonus attribute': ('strength', 'dexterity'), 
                    'weapon properties': ['finesse', 'light']}, 
    'war pick': {'weapon type': 'martial', 
                 'damage die': (8,), 
                 'damage type': 'piercing', 
                 'bonus attribute': 'strength', 
                 'weapon properties': []}, 
    'whip': {'weapon type': 'martial', 
             'damage die': (4,), 
             'damage type': 'slashing', 
             'bonus attribute': ('strength', 'dexterity'), 
             'weapon properties': ['finesse', 'reach']}
}

ranged_weapon_stats = {
    'light crossbow': {'weapon type': 'simple', 
                       'damage die': (8,), 
                       'damage type': 'piercing', 
                       'bonus attribute': 'dexterity', 
                       'weapon properties': ['ammunition', 'ranged', 'loading', 'two handed'], 
                       'range': (80, 320)}, 
    'dart': {'weapon type': 
             'simple', 'damage die': (4,), 
             'damage type': 'piercing', 
             'bonus attribute': 'dexterity', 
             'weapon properties': ['finesse', 'thrown'], 
             'range': (20, 60)}, 
    'short bow': {'weapon type': 'simple', 
                  'damage die': (6,), 
                  'damage type': 'piercing', 
                  'bonus attribute': 'dexterity', 
                  'weapon properties': ['ammunition', 'ranged', 'two handed'], 
                  'range': (80, 320)}, 
    'sling': {'weapon type': 'simple', 
              'damage die': (4,), 
              'damage type': 'bludgeoning', 
              'bonus attribute': 'dexterity', 
              'weapon properties': ['ammunition', 'ranged'], 
              'range': (80, 320)}, 
    'blow gun': {'weapon type': 'martial', 
                 'damage die': (1,), 
                 'damage type': 'piercing', 
                 'bonus attribute': 'dexterity', 
                 'weapon properties': ['ammunition', 'ranged', 'loading'], 
                 'range': (25, 100)}, 
    'hand crossbow': {'weapon type': 'martial', 
                      'damage die': (6,), 
                      'damage type': 'piercing', 
                      'bonus attribute': 'dexterity', 
                      'weapon properties': ['ammunition', 'ranged', 'light', 'loading'], 
                      'range': (30, 120)}, 
    'heavy crossbow': {'weapon type': 'martial', 
                       'damage die': (10,), 
                       'damage type': 'piercing', 
                       'bonus attribute': 'dexterity', 
                       'weapon properties': ['ammunition', 'ranged', 'heavy', 'loading', 'two handed'], 
                       'range': (100, 400)}, 
    'long bow': {'weapon type': 'martial', 
                 'damage die': (8,), 
                 'damage type': 'piercing', 
                 'bonus attribute': 'dexterity', 
                 'weapon properties': ['ammunition', 'ranged', 'heavy', 'two handed'], 
                 'range': (150, 600)}, 
    'net': {'weapon type': 'martial', 
            'damage die': (8,), 
            'damage type': 'piercing', 
            'bonus attribute': 'dexterity', 
            'weapon properties': ['special:', 'thrown'], 
            'range': (5, 15)},
    'dagger': {'weapon type': 'simple', 
               'damage die': (4,), 
               'damage type': 'piercing', 
               'bonus attribute': ('strength', 'dexterity'), 
               'weapon properties': ['finesse', 'light', 'thrown'], 
               'range': (20, 60)}, 
    'handaxe': {'weapon type': 'simple', 
                'damage die': (6,), 
                'damage type': 'slashing', 
                'bonus attribute': 'strength', 
                'weapon properties': ['light', 'thrown'], 
                'range': (20, 60)}, 
    'javelin': {'weapon type': 'simple', 
                'damage die': (6,), 
                'damage type': 'piercing', 
                'bonus attribute': 'strength', 
                'weapon properties': ['thrown'], 
                'range': (30, 120)}, 
    'light hammer': {'weapon type': 'simple', 
                     'damage die': (4,), 
                     'damage type': 'bludgeoning', 
                     'bonus attribute': 'strength', 
                     'weapon properties': ['light', 'thrown'], 
                     'range': (20, 60)}
    }

versatile_melee_weapon_stats = {
    'quarterstaff': {'weapon type': 'simple', 
                     'damage die': (6,), 
                     'damage type': 'bludgeoning', 
                     'bonus attribute': 'strength', 
                     'weapon properties': ['versatile'], 
                     'two handed damage die': (8,)}, 
    'battle axe': {'weapon type': 'martial', 
                   'damage die': (8,), 
                   'damage type': 'slashing', 
                   'bonus attribute': 'strength', 
                   'weapon properties': ['versatile'], 
                   'two handed damage die': (10,)}, 
    'long sword': {'weapon type': 'martial', 
                   'damage die': (8,), 
                   'damage type': 'slashing', 
                   'bonus attribute': 'strength', 
                   'weapon properties': ['versatile'], 
                   'two handed damage die': (10,)}, 
    'warhammer': {'weapon type': 'martial', 
                  'damage die': (8,), 
                  'damage type': 'bludgeoning', 
                  'bonus attribute': 'strength', 
                  'weapon properties': ['versatile'], 
                  'two handed damage die': (10,)}
    }

veratile_ranged_weapon_stats = {
    'trident': {'weapon type': 'martial', 
                'damage die': (6,), 
                'damage type': 'piercing', 
                'bonus attribute': 'strength', 
                'weapon properties': ['thrown', 'versatile'], 
                'range': (20, 60), 
                'two handed damage die': (8,)}, 
    'spear': {'weapon type': 'simple', 
              'damage die': (6,), 
              'damage type': 'piercing', 
              'bonus attribute': 'strength', 
              'weapon properties': ['thrown', 'versatile'], 
              'range': (20, 60), 'two handed damage die': (8,)}}

armor_stats = {
    "padded": {"armor type": "light",
               "ac": 11,
               "dex mod": True,
               "dex max": None,
               "stealth disadvantage": True,
               "strength requirement": None},
    "leather": {"armor type": "light",
               "ac": 11,
               "dex mod": True,
               "dex max": None,
               "stealth disadvantage": False,
               "strength requirement": None},
    "studded leather": {"armor type": "light",
               "ac": 12,
               "dex mod": True,
               "dex max": None,
               "stealth disadvantage": False,
               "strength requirement": None},
    "hide": {"armor type": "medium",
               "ac": 12,
               "dex mod": True,
               "dex max": 2,
               "stealth disadvantage": False,
               "strength requirement": None},
    "chain shirt": {"armor type": "medium",
               "ac": 13,
               "dex mod": True,
               "dex max": 2,
               "stealth disadvantage": False,
               "strength requirement": None},
    "scale mail": {"armor type": "medium",
               "ac": 14,
               "dex mod": True,
               "dex max": 2,
               "stealth disadvantage": True,
               "strength requirement": None},
    "breastplate": {"armor type": "medium",
               "ac": 14,
               "dex mod": True,
               "dex max": 2,
               "stealth disadvantage": False,
               "strength requirement": None},
    "half plate": {"armor type": "medium",
               "ac": 15,
               "dex mod": True,
               "dex max": 2,
               "stealth disadvantage": True,
               "strength requirement": None},
    "ring mail": {"armor type": "heavy",
               "ac": 14,
               "dex mod": False,
               "dex max": None,
               "stealth disadvantage": True,
               "strength requirement": None},
    "chain mail": {"armor type": "heavy",
               "ac": 16,
               "dex mod": False,
               "dex max": None,
               "stealth disadvantage": True,
               "strength requirement": 13},
    "splint": {"armor type": "heavy",
               "ac": 17,
               "dex mod": False,
               "dex max": None,
               "stealth disadvantage": True,
               "strength requirement": 15},
    "splint": {"armor type": "heavy",
               "ac": 18,
               "dex mod": False,
               "dex max": None,
               "stealth disadvantage": True,
               "strength requirement": 15},
    "shield": {"armor type": "shield",
               "ac": 2,
               "dex mod": False,
               "dex max": None,
               "stealth disadvantage": False,
               "strength requirement": None},
}

weapon_property_descriptions = {
    "ammunition": "Ammunition: requires ammo to use, one ammo per use.",
    "finesse": "Finesse: choose whether to use strength or dex modifier for attack and damage rolls",
    "heavy": "Heavy: small and tiny creatures have disacvantage on attack rolls",
    "light": "Light: ideal for two weapon fighting",
    "loading": "Loading: you can fire only one piece of ammo when you use an action, bonus action or reaction, regardless of how many attacks you have.",
    "ranged": "Ranged: ranged weapon, with normal and long range. When attacking beyond normal range you have disadvantage",
    "reach": "Reach: add 5 feet to your reach while using this weapon",
    "special": "Special:",
    "thrown": "Thrown: throw this weapon for a ranged attack, using same modifier as a melee attack with this weapon.",
    "two handed": "Two Handed: requires two hands to wield",
    "versatile": "Versatile: can be used with one or two hands, rolling a different damage die for each option"
}

