from fillpdf import fillpdfs
import os

template_path = "/root/workspace/github.com/CoDanTheBarbarian/5e_character_creator/pdf/Character_Sheet_Template.pdf"
output_path = "/root/workspace/github.com/CoDanTheBarbarian/5e_character_creator/pdf/"

fields_key = {
          'text_1lehv': "name", 
          'text_2doro': "background", 
          'text_3jvjj': "class", 
          'text_4htxk': "race", 
          'text_5fclu': "subclass", 
          'text_6mtop': "level", 
          'text_7bcgp': "xp", 
          'text_8lyot': "ac", 
          'text_9pwko': "current hp", 
          'text_10jsjd': "temp hp", 
          'text_11gboc': "max hp", 
          'text_12mirk': "max hit die", 
          'text_13lfku': "spent hit die", 
          'text_14bhlv': "initiative", 
          'text_15vogh': "speed", 
          'text_16xvdf': "size", 
          'text_17tqcv': "passive perception", 
          'text_18kwvv': "proficiency bonus", 
          'text_19gtct': "strength modifier", 
          'text_20bied': "strength score", 
          'text_21iypl': "intelligence modifer", 
          'text_22pxug': "intelligence score", 
          'text_23asuc': "dexterity modifier", 
          'text_24hmmb': "dexterity score", 
          'text_25ncji': "wisdom modifier", 
          'text_26rbzy': "wisdom score", 
          'text_27qfiv': "constitution modifier", 
          'text_28obur': "constitution score", 
          'text_29zmye': "charisma modifier", 
          'text_30jwsx': "charisma score", 
          'text_31vooh': "acrobatics modifier", 
          'text_32pbxr': "medicine modifier", 
          'text_33tvee': "animal handling modifier", 
          'text_34issc': "arcana modifier", 
          'text_36mpnv': "athletics modifier", 
          'text_37tgqo': "deception modifier", 
          'text_38kvjm': "history modifier", 
          'text_39mmaz': "insight modifier", 
          'text_40vhrl': "intimidation modifier", 
          'text_41lfru': "investigation modifier", 
          'text_42qddx': "nature modifier", 
          'text_44dklr': "perception modifier", 
          'text_45rdl': "performance modifier", 
          'text_46zlii': "persausion modifier", 
          'text_47mtrc': "religion modifier", 
          'text_48wwut': "sleight of hand modifier", 
          'text_49ztsd': "stealth modifier", 
          'text_50fkah': "survival modifier", 
          'text_213vjaj': "weapon 1 name", 
          'text_214lfis': "weapon 2 name", 
          'text_215afnf': "weapon 3 name", 
          'text_216prrs': "weapon 4 name", 
          'text_217iamf': "weapon 5 name", 
          'text_218hjoz': "weapon 6 name", 
          'text_219ameb': "weapon 1 attack bonus/dc", 
          'text_220apjo': "weapon 2 attack bonus/dc", 
          'text_221fixh': "weapon 3 attack bonus/dc", 
          'text_222odvz': "weapon 4 attack bonus/dc", 
          'text_223adiy': "weapon 5 attack bonus/dc", 
          'text_224rbdd': "weapon 6 attack bonus/dc", 
          'text_225fptj': "weapon 1 damage type", 
          'text_226ujth': "weapon 2 damage type", 
          'text_227tuqa': "weapon 3 damage type", 
          'text_228dnel': "weapon 4 damage type", 
          'text_229ftkg': "weapon 5 damage type", 
          'text_230jtwi': "weapon 6 damage type", 
          'text_231piki': "weapon 1 notes", 
          'text_232qdk': "weapon 2 notes", 
          'text_233pfmo': "weapon 3 notes", 
          'text_234zuob': "weapon 4 notes", 
          'text_235akii': "weapon 5 notes", 
          'text_236hoqa': "weapon 6 notes", 
          'textarea_237vdig': "class features box 1", 
          'textarea_238rkrv': "class features box 2", 
          'textarea_239zoqi': "race traits", 
          'textarea_240ngth': "feats", 
          'textarea_245bjob': "tools", 
          'textarea_246zssm': "weapons", 
          'text_247iukc': "constition saving throw", 
          'text_248bhjr': "charisma saving throw", 
          'text_249radr': "wisdom saving throw", 
          'text_250qfah': "dexterity saving throw", 
          'text_251sjko': "strength saving throw", 
          'text_252xwpl': "intelligence saving throw", 
          'checkbox_253xxbz': 'Yes_sslz', 
          'checkbox_254dvqi': 'Yes_sslz', 
          'checkbox_255fxix': 'Yes_sslz', 
          'checkbox_256qosr': 'Yes_sslz', 
          'checkbox_257yypo': 'Yes_sslz', 
          'checkbox_258nvba': 'Yes_sslz', 
          'checkbox_259qthz': 'Yes_sslz', 
          'checkbox_260gwym': 'Yes_sslz', 
          'checkbox_261jsmo': 'Yes_sslz', 
          'checkbox_262pcmc': 'Yes_sslz', 
          'checkbox_263qcjm': 'Yes_sslz', 
          'checkbox_264mtuo': 'Yes_sslz', 
          'checkbox_265jdcj': 'Yes_sslz', 
          'checkbox_266dqtq': 'Yes_sslz', 
          'checkbox_267oon': 'Yes_sslz', 
          'checkbox_268hgzb': 'Yes_sslz', 
          'checkbox_269gfuh': 'Yes_sslz', 
          'checkbox_270sldd': 'Yes_sslz', 
          'checkbox_271zckg': 'Yes_sslz', 
          'checkbox_272klip': 'Yes_sslz', 
          'checkbox_273svvi': 'Yes_sslz', 
          'checkbox_274ojmj': 'Yes_sslz', 
          'checkbox_275jirm': 'Yes_sslz', 
          'checkbox_276upbq': 'Yes_sslz', 
          'checkbox_277cvsc': 'Yes_sslz', 
          'checkbox_278xefp': 'Yes_sslz', 
          'checkbox_279kstn': 'Yes_sslz', 
          'checkbox_280mvjc': 'Yes_sslz', 
          'checkbox_281mxvf': 'Yes_sslz', 
          'checkbox_282phlb': 'Yes_sslz', 
          'checkbox_283zucn': 'Yes_sslz', 
          'checkbox_284pedi': 'Yes_sslz', 
          'checkbox_285zjte': 'Yes_sslz', 
          'checkbox_286tyof': 'Yes_sslz', 
          'checkbox_415wdfd': 'Yes_ahzd', 
          'text_51soru': "spellcasting modifier", 
          'text_52xzcj': "spell save dc", 
          'text_53trsa': "spell attack bonus", 
          'text_54owlm': "spell:1 level", 
          'text_55khjy': "spell:2 level", 
          'text_56cqkp': "spell:3 level", 
          'text_57kizl': "spell:4 level", 
          'text_58qbhe': "spell:5 level", 
          'text_59dob': "spell:6 level", 
          'text_60uxsd': "spell:7 level", 
          'text_61aqjt': "spell:8 level", 
          'text_62tfry': "spell:9 level", 
          'text_63sxzn': "spell:10 level", 
          'text_64nsdz': "spell:11 level", 
          'text_65inea': "spell:12 level", 
          'text_66ulko': "spell:13 level", 
          'text_67yciq': "spell:14 level", 
          'text_68liiz': "spell:15 level", 
          'text_69sxis': "spell:16 level", 
          'text_70lywd': "spell:17 level", 
          'text_71nhyk': "spell:18 level", 
          'text_72syfu': "spell:19 level", 
          'text_73iywe': "spell:20 level", 
          'text_74zqxx': "spell:21 level", 
          'text_75nhdb': "spell:22 level", 
          'text_76tcyf': "spell:23 level", 
          'text_77lggp': "spell:24 level", 
          'text_78tif': "spell:25 level", 
          'text_79nnst': "spell:26 level", 
          'text_80zaxi': "spell:27 level", 
          'text_81flxb': "spell:28 level", 
          'text_82jrtf': "spell:29 level", 
          'text_83nwxr': "spell:30 level", 
          'text_84ewwp': "spell:1 casting time", 
          'text_85tc': "spell:2 casting time", 
          'text_86cdpi': "spell:3 casting time", 
          'text_87dktp': "spell:4 casting time", 
          'text_88uwjf': "spell:5 casting time", 
          'text_89vprr': "spell:6 casting time", 
          'text_90slur': "spell:7 casting time", 
          'text_91ucqk': "spell:8 casting time", 
          'text_92evac': "spell:9 casting time", 
          'text_93epci': "spell:10 casting time", 
          'text_94weto': "spell:11 casting time", 
          'text_95xget': "spell:12 casting time", 
          'text_96cipd': "spell:13 casting time", 
          'text_97mlkz': "spell:14 casting time", 
          'text_98olmq': "spell:15 casting time", 
          'text_99mfgo': "spell:16 casting time", 
          'text_100gzjm': "spell:17 casting time",
          'text_101yovg': "spell:18 casting time", 
          'text_102hrxl': "spell:19 casting time", 
          'text_103vhww': "spell:20 casting time", 
          'text_104wwz': "spell:21 casting time", 
          'text_105dfxp': "spell:22 casting time", 
          'text_106naqd': "spell:23 casting time", 
          'text_107tquy': "spell:24 casting time", 
          'text_108nrbs': "spell:25 casting time", 
          'text_109qsjf': "spell:26 casting time", 
          'text_110plzx': "spell:27 casting time", 
          'text_111dpya': "spell:28 casting time", 
          'text_112ilmj': "spell:29 casting time", 
          'text_113vquk': "spell:30 casting time", 
          'text_114qoqr': "spell:1 name", 
          'text_115rugb': "spell:2 name", 
          'text_116hduf': "spell:3 name", 
          'text_117djzw': "spell:4 name", 
          'text_118ippm': "spell:5 name", 
          'text_119fqqs': "spell:6 name", 
          'text_120hyts': "spell:7 name", 
          'text_121rxog': "spell:8 name", 
          'text_122upth': "spell:9 name", 
          'text_123bqjt': "spell:10 name", 
          'text_124cvmw': "spell:11 name", 
          'text_125lray': "spell:12 name", 
          'text_126ogsn': "spell:13 name", 
          'text_127myvj': "spell:14 name", 
          'text_128jljs': "spell:15 name", 
          'text_129eony': "spell:16 name", 
          'text_130xovf': "spell:17 name", 
          'text_131kmf': "spell:18 name", 
          'text_132sdy': "spell:19 name", 
          'text_133qshw': "spell:20 name", 
          'text_134pxnx': "spell:21 name", 
          'text_135zpeh': "spell:22 name", 
          'text_136jowj': "spell:23 name", 
          'text_137lewk': "spell:24 name", 
          'text_138zxvv': "spell:25 name", 
          'text_139bbbo': "spell:26 name", 
          'text_140dlrc': "spell:27 name", 
          'text_141tzdo': "spell:28 name", 
          'text_142vuxp': "spell:29 name", 
          'text_143urgz': "spell:30 name", 
          'text_144xjax': "spell:1 range", 
          'text_145qoyt': "spell:2 range", 
          'text_146nrfg': "spell:3 range", 
          'text_147jgjf': "spell:4 range", 
          'text_148srjj': "spell:5 range", 
          'text_149nhcb': "spell:6 range", 
          'text_150xnzb': "spell:7 range", 
          'text_151rejf': "spell:8 range",
          'text_152kkgc': "spell:9 range", 
          'text_153iafo': "spell:10 range", 
          'text_154dlrr': "spell:11 range", 
          'text_155defd': "spell:12 range", 
          'text_156icda': "spell:13 range", 
          'text_157kazy': "spell:14 range", 
          'text_158xhag': "spell:15 range", 
          'text_159wsdw': "spell:16 range", 
          'text_160xhyq': "spell:17 range", 
          'text_161dmdk': "spell:18 range", 
          'text_162ddxw': "spell:19 range", 
          'text_163rgxd': "spell:20 range", 
          'text_164wpn': "spell:21 range", 
          'text_165fhei': "spell:22 range", 
          'text_166vdsf': "spell:23 range", 
          'text_167gyfn': "spell:24 range", 
          'text_168qtyo': "spell:25 range", 
          'text_169akno': "spell:26 range", 
          'text_170gswt': "spell:27 range", 
          'text_171hreg': "spell:28 range", 
          'text_172bse': "spell:29 range", 
          'text_173igxz': "spell:30 range", 
          'text_174vybk': "spell:1 notes", 
          'text_175syga': "spell:2 notes", 
          'text_176ovnl': "spell:3 notes", 
          'text_177apis': "spell:4 notes", 
          'text_178yrri': "spell:5 notes", 
          'text_179zepm': "spell:6 notes", 
          'text_180viwi': "spell:7 notes", 
          'text_181oatm': "spell:8 notes",
          'text_182sibc': "spell:9 notes", 
          'text_183ssns': "spell:10 notes", 
          'text_184zfz': "spell:11 notes", 
          'text_185sttb': "spell:12 notes", 
          'text_186wamj': "spell:13 notes", 
          'text_187npzm': "spell:14 notes", 
          'text_188yyyw': "spell:15 notes", 
          'text_189kbhl': "spell:16 notes", 
          'text_190juoh': "spell:17 notes", 
          'text_191cvvi': "spell:18 notes", 
          'text_192gbqj': "spell:19 notes", 
          'text_193gfag': "spell:20 notes", 
          'text_194rert': "spell:21 notes", 
          'text_195yzuc': "spell:22 notes", 
          'text_196cdrh': "spell:23 notes", 
          'text_197ns': "spell:24 notes", 
          'text_198jtmw': "spell:25 notes", 
          'text_199ccon': "spell:26 notes", 
          'text_200mcnb': "spell:27 notes", 
          'text_201koff': "spell:28 notes", 
          'text_202npow': "spell:29 notes", 
          'text_203dsbx': "spell:30 notes", 
          'text_204qtpv': "magic item attunement slot 1: name", 
          'text_205ripg': "magic item attunement slot 2: name", 
          'text_206tilr': "magic item attunement slot 3: name", 
          'text_207jfes': "copper pieces", 
          'text_208zlpp': "silver pieces", 
          'text_209lziy': "electrum pieces", 
          'text_210hycy': "gold pieces", 
          'text_211gvpa': "platinum pieces", 
          'text_212sxja': "alignment", 
          'textarea_241jbls': "appearance", 
          'textarea_242ttpk': "backstory & personality", 
          'textarea_243xnms': "languages", 
          'textarea_244f': "equipment", 
          'checkbox_287czvv': 'Yes_sslz', 
          'checkbox_288kbbs': 'Yes_sslz', 
          'checkbox_289teda': 'Yes_sslz', 
          'text_290ljfo': "total level 1 spell slots", 
          'text_291hqz': "total level 2 spell slots", 
          'text_292wtyr': "total level 3 spell slots", 
          'text_293irjl': "total level 4 spell slots", 
          'text_294cgul': "total level 5 spell slots", 
          'text_295wrxu': "total level 6 spell slots", 
          'text_296wupa': "total level 7 spell slots", 
          'text_297smxt': "total level 8 spell slots", 
          'text_298hzov': "total level 9 spell slots", 
          'checkbox_302ypbb': 'Yes_vriv', 
          'checkbox_303twtx': 'Yes_vriv', 
          'checkbox_304fbul': 'Yes_vriv', 
          'checkbox_305ydwj': 'Yes_vriv', 
          'checkbox_306jlxu': 'Yes_vriv', 
          'checkbox_307eqvf': 'Yes_vriv', 
          'checkbox_308xpjq': 'Yes_vriv', 
          'checkbox_309xarm': 'Yes_vriv', 
          'checkbox_310ntsi': 'Yes_vriv', 
          'checkbox_311vjaj': 'Yes_vriv', 
          'checkbox_312tmpj': 'Yes_vriv', 
          'checkbox_313sdk': 'Yes_vriv', 
          'checkbox_314djdf': 'Yes_vriv', 
          'checkbox_315swrj': 'Yes_vriv', 
          'checkbox_316dilg': 'Yes_vriv', 
          'checkbox_317xdas': 'Yes_vriv', 
          'checkbox_318lwe': 'Yes_vriv', 
          'checkbox_319eafy': 'Yes_vriv', 
          'checkbox_320yuqi': 'Yes_vriv', 
          'checkbox_321byqj': 'Yes_vriv', 
          'checkbox_322nezk': 'Yes_vriv', 
          'checkbox_323wdjg': 'Yes_vriv', 
          'checkbox_324ibcg': 'Yes_rqlb', 
          'checkbox_325qgob': 'Yes_rqlb', 
          'checkbox_326pnvo': 'Yes_rqlb', 
          'checkbox_327akxy': 'Yes_rqlb', 
          'checkbox_328nffs': 'Yes_rqlb', 
          'checkbox_329cxii': 'Yes_rqlb', 
          'checkbox_330sktt': 'Yes_rqlb',
          'checkbox_331uphf': 'Yes_rqlb', 
          'checkbox_332qbqn': 'Yes_rqlb', 
          'checkbox_333dwmp': 'Yes_rqlb', 
          'checkbox_334lwxr': 'Yes_rqlb', 
          'checkbox_335fezy': 'Yes_rqlb', 
          'checkbox_336esjj': 'Yes_rqlb', 
          'checkbox_337gseq': 'Yes_rqlb', 
          'checkbox_338uftr': 'Yes_rqlb', 
          'checkbox_339amyj': 'Yes_rqlb', 
          'checkbox_340svcj': 'Yes_rqlb', 
          'checkbox_341nltz': 'Yes_rqlb', 
          'checkbox_343beuq': 'Yes_rqlb', 
          'checkbox_344gdzh': 'Yes_rqlb', 
          'checkbox_345haat': 'Yes_rqlb', 
          'checkbox_346ptis': 'Yes_rqlb', 
          'checkbox_347kknk': 'Yes_rqlb', 
          'checkbox_348lqhd': 'Yes_rqlb', 
          'checkbox_349iogu': 'Yes_rqlb', 
          'checkbox_350imcb': 'Yes_rqlb',
          'checkbox_351izgz': 'Yes_rqlb', 
          'checkbox_352duwl': 'Yes_rqlb', 
          'checkbox_353pzqr': 'Yes_rqlb', 
          'checkbox_354aun': 'Yes_rqlb', 
          'checkbox_355rawb': 'Yes_rqlb', 
          'checkbox_356bauz': 'Yes_rqlb', 
          'checkbox_357fqod': 'Yes_rqlb', 
          'checkbox_358cpt': 'Yes_rqlb', 
          'checkbox_359mlnn': 'Yes_rqlb', 
          'checkbox_360qtas': 'Yes_rqlb', 
          'checkbox_361aoog': 'Yes_rqlb', 
          'checkbox_362jvgv': 'Yes_rqlb', 
          'checkbox_363fbqv': 'Yes_rqlb', 
          'checkbox_364udcu': 'Yes_rqlb', 
          'checkbox_365ggjx': 'Yes_rqlb', 
          'checkbox_366chyp': 'Yes_rqlb', 
          'checkbox_367lxqe': 'Yes_rqlb', 
          'checkbox_368amxh': 'Yes_rqlb', 
          'checkbox_369qezs': 'Yes_rqlb', 
          'checkbox_370tcar': 'Yes_rqlb', 
          'checkbox_371ghv': 'Yes_rqlb', 
          'checkbox_372quix': 'Yes_rqlb', 
          'checkbox_373ifgn': 'Yes_rqlb', 
          'checkbox_374ietr': 'Yes_rqlb', 
          'checkbox_375jtmc': 'Yes_rqlb', 
          'checkbox_376ofhc': 'Yes_rqlb', 
          'checkbox_377xewk': 'Yes_rqlb', 
          'checkbox_378ftqw': 'Yes_rqlb', 
          'checkbox_379cunr': 'Yes_rqlb', 
          'checkbox_380bpjz': 'Yes_rqlb', 
          'checkbox_381bdvq': 'Yes_rqlb', 
          'checkbox_382ilds': 'Yes_rqlb', 
          'checkbox_383aztt': 'Yes_rqlb', 
          'checkbox_384kiug': 'Yes_rqlb', 
          'checkbox_385wltr': 'Yes_rqlb', 
          'checkbox_386bfgm': 'Yes_rqlb', 
          'checkbox_387tbzz': 'Yes_rqlb', 
          'checkbox_388jpp': 'Yes_rqlb', 
          'checkbox_389yptt': 'Yes_rqlb', 
          'checkbox_390dwxa': 'Yes_rqlb', 
          'checkbox_391qnol': 'Yes_rqlb', 
          'checkbox_392ttth': 'Yes_rqlb', 
          'checkbox_393eaol': 'Yes_rqlb', 
          'checkbox_394msib': 'Yes_rqlb', 
          'checkbox_395dnoz': 'Yes_rqlb', 
          'checkbox_396febm': 'Yes_rqlb', 
          'checkbox_397nmbx': 'Yes_rqlb', 
          'checkbox_398ydzu': 'Yes_rqlb', 
          'checkbox_399egyd': 'Yes_rqlb', 
          'checkbox_400epdl': 'Yes_rqlb', 
          'checkbox_401wzuj': 'Yes_rqlb', 
          'checkbox_402xdcv': 'Yes_rqlb', 
          'checkbox_403mavz': 'Yes_rqlb', 
          'checkbox_404exod': 'Yes_rqlb', 
          'checkbox_405uxgy': 'Yes_rqlb', 
          'checkbox_406lfag': 'Yes_rqlb', 
          'checkbox_407exmq': 'Yes_rqlb', 
          'checkbox_408yann': 'Yes_rqlb', 
          'checkbox_409ixpd': 'Yes_rqlb', 
          'checkbox_410waaf': 'Yes_rqlb', 
          'checkbox_411fxga': 'Yes_rqlb', 
          'checkbox_412mkmq': 'Yes_rqlb', 
          'checkbox_413obqz': 'Yes_rqlb', 
          'checkbox_414kfjp': 'Yes_rqlb'
          }


checkbox_yes_values = {
    'checkbox_253xxbz': 'Yes_sslz', 
    'checkbox_254dvqi': 'Yes_sslz', 
    'checkbox_255fxix': 'Yes_sslz', 
    'checkbox_256qosr': 'Yes_sslz', 
    'checkbox_257yypo': 'Yes_sslz', 
    'checkbox_258nvba': 'Yes_sslz', 
    'checkbox_259qthz': 'Yes_sslz', 
    'checkbox_260gwym': 'Yes_sslz', 
    'checkbox_261jsmo': 'Yes_sslz', 
    'checkbox_262pcmc': 'Yes_sslz', 
    'checkbox_263qcjm': 'Yes_sslz', 
    'checkbox_264mtuo': 'Yes_sslz', 
    'checkbox_265jdcj': 'Yes_sslz', 
    'checkbox_266dqtq': 'Yes_sslz', 
    'checkbox_267oon': 'Yes_sslz', 
    'checkbox_268hgzb': 'Yes_sslz', 
    'checkbox_269gfuh': 'Yes_sslz', 
    'checkbox_270sldd': 'Yes_sslz', 
    'checkbox_271zckg': 'Yes_sslz', 
    'checkbox_272klip': 'Yes_sslz', 
    'checkbox_273svvi': 'Yes_sslz', 
    'checkbox_274ojmj': 'Yes_sslz', 
    'checkbox_275jirm': 'Yes_sslz', 
    'checkbox_276upbq': 'Yes_sslz', 
    'checkbox_277cvsc': 'Yes_sslz', 
    'checkbox_278xefp': 'Yes_sslz', 
    'checkbox_279kstn': 'Yes_sslz', 
    'checkbox_280mvjc': 'Yes_sslz', 
    'checkbox_281mxvf': 'Yes_sslz', 
    'checkbox_282phlb': 'Yes_sslz', 
    'checkbox_283zucn': 'Yes_sslz', 
    'checkbox_284pedi': 'Yes_sslz', 
    'checkbox_285zjte': 'Yes_sslz', 
    'checkbox_286tyof': 'Yes_sslz', 
    'checkbox_415wdfd': 'Yes_ahzd', 
    'checkbox_287czvv': 'Yes_sslz', 
    'checkbox_288kbbs': 'Yes_sslz', 
    'checkbox_289teda': 'Yes_sslz', 
    'checkbox_302ypbb': 'Yes_vriv', 
    'checkbox_303twtx': 'Yes_vriv', 
    'checkbox_304fbul': 'Yes_vriv', 
    'checkbox_305ydwj': 'Yes_vriv', 
    'checkbox_306jlxu': 'Yes_vriv', 
    'checkbox_307eqvf': 'Yes_vriv', 
    'checkbox_308xpjq': 'Yes_vriv', 
    'checkbox_309xarm': 'Yes_vriv', 
    'checkbox_310ntsi': 'Yes_vriv', 
    'checkbox_311vjaj': 'Yes_vriv', 
    'checkbox_312tmpj': 'Yes_vriv', 
    'checkbox_313sdk': 'Yes_vriv', 
    'checkbox_314djdf': 'Yes_vriv', 
    'checkbox_315swrj': 'Yes_vriv', 
    'checkbox_316dilg': 'Yes_vriv', 
    'checkbox_317xdas': 'Yes_vriv', 
    'checkbox_318lwe': 'Yes_vriv', 
    'checkbox_319eafy': 'Yes_vriv',
    'checkbox_320yuqi': 'Yes_vriv', 
    'checkbox_321byqj': 'Yes_vriv', 
    'checkbox_322nezk': 'Yes_vriv', 
    'checkbox_323wdjg': 'Yes_vriv', 
    'checkbox_324ibcg': 'Yes_rqlb', 
    'checkbox_325qgob': 'Yes_rqlb', 
    'checkbox_326pnvo': 'Yes_rqlb', 
    'checkbox_327akxy': 'Yes_rqlb', 
    'checkbox_328nffs': 'Yes_rqlb', 
    'checkbox_329cxii': 'Yes_rqlb', 
    'checkbox_330sktt': 'Yes_rqlb', 
    'checkbox_331uphf': 'Yes_rqlb', 
    'checkbox_332qbqn': 'Yes_rqlb', 
    'checkbox_333dwmp': 'Yes_rqlb', 
    'checkbox_334lwxr': 'Yes_rqlb', 
    'checkbox_335fezy': 'Yes_rqlb', 
    'checkbox_336esjj': 'Yes_rqlb', 
    'checkbox_337gseq': 'Yes_rqlb', 
    'checkbox_338uftr': 'Yes_rqlb', 
    'checkbox_339amyj': 'Yes_rqlb', 
    'checkbox_340svcj': 'Yes_rqlb', 
    'checkbox_341nltz': 'Yes_rqlb', 
    'checkbox_343beuq': 'Yes_rqlb', 
    'checkbox_344gdzh': 'Yes_rqlb', 
    'checkbox_345haat': 'Yes_rqlb', 
    'checkbox_346ptis': 'Yes_rqlb', 
    'checkbox_347kknk': 'Yes_rqlb', 
    'checkbox_348lqhd': 'Yes_rqlb', 
    'checkbox_349iogu': 'Yes_rqlb', 
    'checkbox_350imcb': 'Yes_rqlb', 
    'checkbox_351izgz': 'Yes_rqlb', 
    'checkbox_352duwl': 'Yes_rqlb', 
    'checkbox_353pzqr': 'Yes_rqlb', 
    'checkbox_354aun': 'Yes_rqlb', 
    'checkbox_355rawb': 'Yes_rqlb', 
    'checkbox_356bauz': 'Yes_rqlb', 
    'checkbox_357fqod': 'Yes_rqlb', 
    'checkbox_358cpt': 'Yes_rqlb', 
    'checkbox_359mlnn': 'Yes_rqlb', 
    'checkbox_360qtas': 'Yes_rqlb', 
    'checkbox_361aoog': 'Yes_rqlb', 
    'checkbox_362jvgv': 'Yes_rqlb', 
    'checkbox_363fbqv': 'Yes_rqlb', 
    'checkbox_364udcu': 'Yes_rqlb', 
    'checkbox_365ggjx': 'Yes_rqlb', 
    'checkbox_366chyp': 'Yes_rqlb', 
    'checkbox_367lxqe': 'Yes_rqlb', 
    'checkbox_368amxh': 'Yes_rqlb', 
    'checkbox_369qezs': 'Yes_rqlb', 
    'checkbox_370tcar': 'Yes_rqlb', 
    'checkbox_371ghv': 'Yes_rqlb', 
    'checkbox_372quix': 'Yes_rqlb', 
    'checkbox_373ifgn': 'Yes_rqlb', 
    'checkbox_374ietr': 'Yes_rqlb', 
    'checkbox_375jtmc': 'Yes_rqlb', 
    'checkbox_376ofhc': 'Yes_rqlb', 
    'checkbox_377xewk': 'Yes_rqlb', 
    'checkbox_378ftqw': 'Yes_rqlb', 
    'checkbox_379cunr': 'Yes_rqlb', 
    'checkbox_380bpjz': 'Yes_rqlb', 
    'checkbox_381bdvq': 'Yes_rqlb', 
    'checkbox_382ilds': 'Yes_rqlb', 
    'checkbox_383aztt': 'Yes_rqlb', 
    'checkbox_384kiug': 'Yes_rqlb', 
    'checkbox_385wltr': 'Yes_rqlb', 
    'checkbox_386bfgm': 'Yes_rqlb', 
    'checkbox_387tbzz': 'Yes_rqlb', 
    'checkbox_388jpp': 'Yes_rqlb', 
    'checkbox_389yptt': 'Yes_rqlb', 
    'checkbox_390dwxa': 'Yes_rqlb', 
    'checkbox_391qnol': 'Yes_rqlb', 
    'checkbox_392ttth': 'Yes_rqlb', 
    'checkbox_393eaol': 'Yes_rqlb', 
    'checkbox_394msib': 'Yes_rqlb', 
    'checkbox_395dnoz': 'Yes_rqlb', 
    'checkbox_396febm': 'Yes_rqlb', 
    'checkbox_397nmbx': 'Yes_rqlb', 
    'checkbox_398ydzu': 'Yes_rqlb', 
    'checkbox_399egyd': 'Yes_rqlb', 
    'checkbox_400epdl': 'Yes_rqlb', 
    'checkbox_401wzuj': 'Yes_rqlb', 
    'checkbox_402xdcv': 'Yes_rqlb', 
    'checkbox_403mavz': 'Yes_rqlb', 
    'checkbox_404exod': 'Yes_rqlb', 
    'checkbox_405uxgy': 'Yes_rqlb', 
    'checkbox_406lfag': 'Yes_rqlb', 
    'checkbox_407exmq': 'Yes_rqlb', 
    'checkbox_408yann': 'Yes_rqlb', 
    'checkbox_409ixpd': 'Yes_rqlb', 
    'checkbox_410waaf': 'Yes_rqlb', 
    'checkbox_411fxga': 'Yes_rqlb', 
    'checkbox_412mkmq': 'Yes_rqlb', 
    'checkbox_413obqz': 'Yes_rqlb', 
    'checkbox_414kfjp': 'Yes_rqlb'
    }



# function to populate a new data dictionary with the data from the character sheet
def parse_character_sheet_data(character):
    pass

# fillpdfs.write_fillable_pdfs(template_path, output_path, character_data) 